import { type Tuning, Instrument } from "@/resources/types";

export const TUNINGS: Tuning[] = [
  // Bass IV
  {
    id: "4b0",
    name: "Standard",
    instrument: Instrument.Bass,
    stringQty: 4,
    stringTunings: [4, 9, 2, 7],
  },
  {
    id: "4b1",
    name: "Drop D",
    instrument: Instrument.Bass,
    stringQty: 4,
    stringTunings: [2, 9, 2, 7],
  },
  {
    id: "4b2",
    name: "Open D",
    instrument: Instrument.Bass,
    stringQty: 4,
    stringTunings: [2, 9, 2, 6],
  },
  {
    id: "4b3",
    name: "Major thirds - E",
    instrument: Instrument.Bass,
    stringQty: 4,
    stringTunings: [4, 8, 0, 4],
  },
  {
    id: "4b4",
    name: "Fifths - Cello",
    instrument: Instrument.Bass,
    stringQty: 4,
    stringTunings: [0, 2, 7, 9],
  },
  {
    id: "4b5",
    name: "Baritone",
    instrument: Instrument.Bass,
    stringQty: 4,
    stringTunings: [11, 4, 9, 2],
  },
  {
    id: "4b6",
    name: "Baritone Drop",
    instrument: Instrument.Bass,
    stringQty: 4,
    stringTunings: [9, 4, 9, 2],
  },
  // Bass V
  {
    id: "5b0",
    name: "Standard",
    instrument: Instrument.Bass,
    stringQty: 5,
    stringTunings: [11, 4, 9, 2, 7],
  },
  {
    id: "5b1",
    name: "Drop A",
    instrument: Instrument.Bass,
    stringQty: 5,
    stringTunings: [9, 4, 9, 2, 7],
  },
  {
    id: "5b2",
    name: "Perfect Fourths - High",
    instrument: Instrument.Bass,
    stringQty: 5,
    stringTunings: [4, 9, 2, 7, 0],
  },
  {
    id: "5b3",
    name: "P4 - High - Drop D",
    instrument: Instrument.Bass,
    stringQty: 5,
    stringTunings: [2, 9, 2, 7, 0],
  },
  {
    id: "5b4",
    name: "P4 - Low - DropA, Drop D",
    instrument: Instrument.Bass,
    stringQty: 5,
    stringTunings: [9, 2, 9, 2, 7],
  },
  {
    id: "5b5",
    name: "Lövgren Meshuggah",
    instrument: Instrument.Bass,
    stringQty: 5,
    stringTunings: [10, 5, 10, 3, 8],
  },
  {
    id: "5b6",
    name: "Swamp",
    instrument: Instrument.Bass,
    stringQty: 5,
    stringTunings: [6, 11, 4, 9, 2],
  },
  // Bass VI
  {
    id: "6b0",
    name: "Standard Tuning",
    instrument: Instrument.Bass,
    stringQty: 6,
    stringTunings: [11, 4, 9, 2, 7, 0],
  },
  {
    id: "6b1",
    name: "23Hz Abyss",
    instrument: Instrument.Bass,
    stringQty: 6,
    stringTunings: [6, 11, 4, 9, 2, 7],
  },
  {
    id: "6b2",
    name: "Baritone",
    instrument: Instrument.Bass,
    stringQty: 6,
    stringTunings: [11, 4, 9, 2, 6, 11],
  },
  {
    id: "6b3",
    name: "Fripp Fifths",
    instrument: Instrument.Bass,
    stringQty: 6,
    stringTunings: [0, 7, 2, 9, 4, 7],
  },
  {
    id: "6b4",
    name: "Downtuned Fripp Fifths",
    instrument: Instrument.Bass,
    stringQty: 6,
    stringTunings: [4, 11, 6, 1, 8, 11],
  },
  {
    id: "6b5",
    name: "Bass DADGAD",
    instrument: Instrument.Bass,
    stringQty: 6,
    stringTunings: [2, 9, 2, 7, 9, 2],
  },
  {
    id: "6b6",
    name: "Double Drop A",
    instrument: Instrument.Bass,
    stringQty: 6,
    stringTunings: [9, 4, 9, 2, 8, 9],
  },
  // Guitar VI
  {
    id: "6g0",
    name: "Standard",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [4, 9, 2, 7, 11, 4],
  },
  {
    id: "6g1",
    name: "Perfect Fourths",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [4, 9, 2, 7, 0, 5],
  },
  {
    id: "6g2",
    name: "Major Thirds",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [4, 8, 0, 4, 8, 0],
  },
  {
    id: "6g3",
    name: "Open E Major",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [4, 11, 4, 8, 11, 4],
  },
  {
    id: "6g4",
    name: "Drop D",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [2, 9, 2, 7, 11, 4],
  },
  {
    id: "6g5",
    name: "Double Drop D",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [2, 9, 2, 7, 11, 2],
  },
  {
    id: "6g6",
    name: "DADGAD",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [2, 9, 2, 7, 9, 2],
  },
  {
    id: "6g7",
    name: "Fripp Fifths",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [0, 7, 2, 9, 4, 7],
  },
  {
    id: "6g8",
    name: "Sikth",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [8, 8, 1, 6, 10, 3],
  },
  {
    id: "6g9",
    name: "Baritone",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [11, 4, 9, 2, 6, 11],
  },
  {
    id: "6g10",
    name: "Baritone P4",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [11, 4, 9, 2, 7, 0],
  },
  {
    id: "6g11",
    name: "Baritone Drop A",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [9, 4, 9, 2, 6, 11],
  },
  {
    id: "6g12",
    name: "Humanity's Last Breath",
    instrument: Instrument.Guitar,
    stringQty: 6,
    stringTunings: [5, 0, 5, 10, 9, 10],
  },
  // Guitar VII
  {
    id: "7g0",
    name: "Standard",
    instrument: Instrument.Guitar,
    stringQty: 7,
    stringTunings: [11, 4, 9, 2, 7, 11, 4],
  },
  {
    id: "7g1",
    name: "Drop A",
    instrument: Instrument.Guitar,
    stringQty: 7,
    stringTunings: [9, 4, 9, 2, 7, 11, 4],
  },
  {
    id: "7g2",
    name: "Perfect Fourths",
    instrument: Instrument.Guitar,
    stringQty: 7,
    stringTunings: [11, 4, 9, 2, 7, 0, 5],
  },
  {
    id: "7g3",
    name: "P4 - Drop A & D",
    instrument: Instrument.Guitar,
    stringQty: 7,
    stringTunings: [9, 2, 9, 7, 2, 0, 5],
  },
  {
    id: "7g4",
    name: "Open D Major",
    instrument: Instrument.Guitar,
    stringQty: 7,
    stringTunings: [9, 2, 9, 6, 2, 9, 2],
  },
  {
    id: "7g5",
    name: "Drop G, Drop C",
    instrument: Instrument.Guitar,
    stringQty: 7,
    stringTunings: [7, 0, 7, 5, 0, 9, 2],
  },
  {
    id: "7g6",
    name: "VIII - Low",
    instrument: Instrument.Guitar,
    stringQty: 7,
    stringTunings: [6, 11, 4, 9, 2, 7, 11],
  },
  {
    id: "7g7",
    name: "ADADGAD",
    instrument: Instrument.Guitar,
    stringQty: 7,
    stringTunings: [9, 2, 9, 2, 7, 9, 2],
  },
  // Guitar VIII
  {
    id: "8g0",
    name: "Standard",
    instrument: Instrument.Guitar,
    stringQty: 8,
    stringTunings: [6, 11, 4, 9, 2, 7, 11, 4],
  },
  {
    id: "8g1",
    name: "Drop E",
    instrument: Instrument.Guitar,
    stringQty: 8,
    stringTunings: [4, 11, 4, 9, 2, 7, 11, 4],
  },
  {
    id: "8g2",
    name: "F Standard",
    instrument: Instrument.Guitar,
    stringQty: 8,
    stringTunings: [5, 10, 3, 8, 1, 6, 10, 3],
  },
  {
    id: "8g3",
    name: "Perfect Fourths",
    instrument: Instrument.Guitar,
    stringQty: 8,
    stringTunings: [6, 11, 4, 9, 2, 7, 0, 5],
  },
  {
    id: "8g4",
    name: "Open - C Major",
    instrument: Instrument.Guitar,
    stringQty: 8,
    stringTunings: [4, 0, 7, 0, 7, 4, 0, 4],
  },
  {
    id: "8g5",
    name: "Granddad Dadgad",
    instrument: Instrument.Guitar,
    stringQty: 8,
    stringTunings: [2, 9, 2, 2, 9, 7, 9, 2],
  },
  {
    id: "8g6",
    name: "IÄ IÄ Cthulhu Fhtagn",
    instrument: Instrument.Guitar,
    stringQty: 8,
    stringTunings: [4, 9, 4, 9, 2, 7, 9, 4],
  },
  {
    id: "8g7",
    name: "9 String Standard Low",
    instrument: Instrument.Guitar,
    stringQty: 8,
    stringTunings: [1, 6, 11, 4, 9, 2, 7, 11],
  },
] as const;
