import { Instruments, type TuningsMap } from "@/resources/types";
import { type StringQty } from "@/resources/themes";

export const TUNINGS: TuningsMap = {
  [Instruments.Guitar]: {
    6: [
      {
        id: "6g0",
        name: "Standard",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [4, 9, 2, 7, 11, 4],
      },
      {
        id: "6g1",
        name: "Perfect Fourths",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [4, 9, 2, 7, 0, 5],
      },
      {
        id: "6g2",
        name: "Major Thirds",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [4, 8, 0, 4, 8, 0],
      },
      {
        id: "6g3",
        name: "Open E Major",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [4, 11, 4, 8, 11, 4],
      },
      {
        id: "6g4",
        name: "Drop D",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [2, 9, 2, 7, 11, 4],
      },
      {
        id: "6g5",
        name: "Double Drop D",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [2, 9, 2, 7, 11, 2],
      },
      {
        id: "6g6",
        name: "DADGAD",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [2, 9, 2, 7, 9, 2],
      },
      {
        id: "6g7",
        name: "Fripp Fifths",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [0, 7, 2, 9, 4, 7],
      },
      {
        id: "6g8",
        name: "Sikth",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [8, 8, 1, 6, 10, 3],
      },
      {
        id: "6g9",
        name: "Baritone",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [11, 4, 9, 2, 6, 11],
      },
      {
        id: "6g10",
        name: "Baritone P4",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [11, 4, 9, 2, 7, 0],
      },
      {
        id: "6g11",
        name: "Baritone Drop A",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [9, 4, 9, 2, 6, 11],
      },
      {
        id: "6g12",
        name: "Humanity's Last Breath",
        instrument: Instruments.Guitar,
        stringQty: 6,
        stringTunings: [4, 11, 4, 9, 8, 9],
      },
    ],
    7: [
      {
        id: "7g0",
        name: "Standard",
        instrument: Instruments.Guitar,
        stringQty: 7,
        stringTunings: [11, 4, 9, 2, 7, 11, 4],
      },
      {
        id: "7g1",
        name: "Drop A",
        instrument: Instruments.Guitar,
        stringQty: 7,
        stringTunings: [9, 4, 9, 2, 7, 11, 4],
      },
      {
        id: "7g2",
        name: "Perfect Fourths",
        instrument: Instruments.Guitar,
        stringQty: 7,
        stringTunings: [11, 4, 9, 2, 7, 0, 5],
      },
      {
        id: "7g3",
        name: "P4 - Drop A & D",
        instrument: Instruments.Guitar,
        stringQty: 7,
        stringTunings: [9, 2, 9, 2, 7, 0, 5],
      },
      {
        id: "7g4",
        name: "Open D Major",
        instrument: Instruments.Guitar,
        stringQty: 7,
        stringTunings: [9, 2, 9, 2, 6, 9, 2],
      },
      {
        id: "7g5",
        name: "Drop G, Drop C",
        instrument: Instruments.Guitar,
        stringQty: 7,
        stringTunings: [7, 0, 7, 0, 5, 9, 2],
      },
      {
        id: "7g6",
        name: "VIII - Low",
        instrument: Instruments.Guitar,
        stringQty: 7,
        stringTunings: [6, 11, 4, 9, 2, 7, 11],
      },
      {
        id: "7g7",
        name: "ADADGAD",
        instrument: Instruments.Guitar,
        stringQty: 7,
        stringTunings: [9, 2, 9, 2, 7, 9, 2],
      },
    ],
    8: [
      {
        id: "8g0",
        name: "Standard",
        instrument: Instruments.Guitar,
        stringQty: 8,
        stringTunings: [6, 11, 4, 9, 2, 7, 11, 4],
      },
      {
        id: "8g1",
        name: "Drop E",
        instrument: Instruments.Guitar,
        stringQty: 8,
        stringTunings: [4, 11, 4, 9, 2, 7, 11, 4],
      },
      {
        id: "8g2",
        name: "F Standard",
        instrument: Instruments.Guitar,
        stringQty: 8,
        stringTunings: [5, 10, 3, 8, 1, 6, 10, 3],
      },
      {
        id: "8g3",
        name: "Perfect Fourths",
        instrument: Instruments.Guitar,
        stringQty: 8,
        stringTunings: [6, 11, 4, 9, 2, 7, 0, 5],
      },
      {
        id: "8g4",
        name: "Open - C Major",
        instrument: Instruments.Guitar,
        stringQty: 8,
        stringTunings: [4, 0, 7, 0, 7, 4, 0, 4],
      },
      {
        id: "8g5",
        name: "Granddad Dadgad",
        instrument: Instruments.Guitar,
        stringQty: 8,
        stringTunings: [2, 9, 2, 9, 2, 7, 9, 2],
      },
      {
        id: "8g6",
        name: "IÄ IÄ Cthulhu Fhtagn",
        instrument: Instruments.Guitar,
        stringQty: 8,
        stringTunings: [4, 9, 4, 9, 2, 4, 9, 2],
      },
      {
        id: "8g7",
        name: "9 String Standard Low",
        instrument: Instruments.Guitar,
        stringQty: 8,
        stringTunings: [1, 6, 11, 4, 9, 2, 7, 11],
      },
      {
        id: "8g8",
        name: "Double Drop Fourths",
        instrument: Instruments.Guitar,
        stringQty: 8,
        stringTunings: [4, 9, 4, 9, 2, 7, 0, 5],
      },
    ],
    9: [
      {
        id: "9g0",
        name: "Standard",
        instrument: Instruments.Guitar,
        stringQty: 9,
        stringTunings: [1, 6, 11, 4, 9, 2, 7, 11, 4],
      },
      {
        id: "9g1",
        name: "Drop B",
        instrument: Instruments.Guitar,
        stringQty: 9,
        stringTunings: [11, 6, 11, 4, 9, 2, 7, 11, 4],
      },
      {
        id: "9g2",
        name: "High Standard",
        instrument: Instruments.Guitar,
        stringQty: 9,
        stringTunings: [6, 11, 4, 9, 2, 7, 11, 4, 9],
      },
      {
        id: "9g3",
        name: "Augmented 5ths",
        instrument: Instruments.Guitar,
        stringQty: 9,
        stringTunings: [8, 0, 4, 8, 0, 4, 8, 0, 4],
      },
      {
        id: "9g4",
        name: "Bass+Guitar",
        instrument: Instruments.Guitar,
        stringQty: 9,
        stringTunings: [11, 4, 9, 2, 7, 0, 5, 9, 2],
      },
    ],
    10: [
      {
        id: "10g0",
        name: "Standard",
        instrument: Instruments.Guitar,
        stringQty: 10,
        stringTunings: [8, 1, 6, 11, 4, 9, 2, 7, 11, 4],
      },
    ],
  },
  [Instruments.Bass]: {
    4: [
      {
        id: "4b0",
        name: "Standard",
        instrument: Instruments.Bass,
        stringQty: 4,
        stringTunings: [4, 9, 2, 7],
      },
      {
        id: "4b1",
        name: "Drop D",
        instrument: Instruments.Bass,
        stringQty: 4,
        stringTunings: [2, 9, 2, 7],
      },
      {
        id: "4b2",
        name: "Open D",
        instrument: Instruments.Bass,
        stringQty: 4,
        stringTunings: [2, 9, 2, 6],
      },
      {
        id: "4b3",
        name: "Major thirds - E",
        instrument: Instruments.Bass,
        stringQty: 4,
        stringTunings: [4, 8, 0, 4],
      },
      {
        id: "4b4",
        name: "Fifths - Cello",
        instrument: Instruments.Bass,
        stringQty: 4,
        stringTunings: [0, 2, 7, 9],
      },
      {
        id: "4b5",
        name: "Baritone",
        instrument: Instruments.Bass,
        stringQty: 4,
        stringTunings: [11, 4, 9, 2],
      },
      {
        id: "4b6",
        name: "Baritone Drop",
        instrument: Instruments.Bass,
        stringQty: 4,
        stringTunings: [9, 4, 9, 2],
      },
    ],
    5: [
      {
        id: "5b0",
        name: "Standard",
        instrument: Instruments.Bass,
        stringQty: 5,
        stringTunings: [11, 4, 9, 2, 7],
      },
      {
        id: "5b1",
        name: "Drop A",
        instrument: Instruments.Bass,
        stringQty: 5,
        stringTunings: [9, 4, 9, 2, 7],
      },
      {
        id: "5b2",
        name: "Perfect Fourths - High",
        instrument: Instruments.Bass,
        stringQty: 5,
        stringTunings: [4, 9, 2, 7, 0],
      },
      {
        id: "5b3",
        name: "P4 - High - Drop D",
        instrument: Instruments.Bass,
        stringQty: 5,
        stringTunings: [2, 9, 2, 7, 0],
      },
      {
        id: "5b4",
        name: "P4 - Low - DropA, Drop D",
        instrument: Instruments.Bass,
        stringQty: 5,
        stringTunings: [9, 2, 9, 2, 7],
      },
      {
        id: "5b5",
        name: "Lövgren Meshuggah",
        instrument: Instruments.Bass,
        stringQty: 5,
        stringTunings: [10, 5, 10, 3, 8],
      },
      {
        id: "5b6",
        name: "Swamp",
        instrument: Instruments.Bass,
        stringQty: 5,
        stringTunings: [6, 11, 4, 9, 2],
      },
    ],
    6: [
      {
        id: "6b0",
        name: "Standard Tuning",
        instrument: Instruments.Bass,
        stringQty: 6,
        stringTunings: [11, 4, 9, 2, 7, 0],
      },
      {
        id: "6b1",
        name: "23Hz Abyss",
        instrument: Instruments.Bass,
        stringQty: 6,
        stringTunings: [6, 11, 4, 9, 2, 7],
      },
      {
        id: "6b2",
        name: "Baritone",
        instrument: Instruments.Bass,
        stringQty: 6,
        stringTunings: [11, 4, 9, 2, 6, 11],
      },
      {
        id: "6b3",
        name: "Fripp Fifths",
        instrument: Instruments.Bass,
        stringQty: 6,
        stringTunings: [0, 7, 2, 9, 4, 7],
      },
      {
        id: "6b4",
        name: "Downtuned Fripp Fifths",
        instrument: Instruments.Bass,
        stringQty: 6,
        stringTunings: [4, 11, 6, 1, 8, 11],
      },
      {
        id: "6b5",
        name: "Bass DADGAD",
        instrument: Instruments.Bass,
        stringQty: 6,
        stringTunings: [2, 9, 2, 7, 9, 2],
      },
      {
        id: "6b6",
        name: "Double Drop A",
        instrument: Instruments.Bass,
        stringQty: 6,
        stringTunings: [9, 4, 9, 2, 8, 9],
      },
    ],
    7: [
      {
        id: "7b0",
        name: "Standard",
        instrument: Instruments.Bass,
        stringQty: 7,
        stringTunings: [11, 4, 9, 2, 7, 0, 5],
      },
      {
        id: "7b1",
        name: "Standard Low",
        instrument: Instruments.Bass,
        stringQty: 7,
        stringTunings: [6, 11, 4, 9, 2, 7, 0],
      },
      {
        id: "7b2",
        name: "Low Guitar",
        instrument: Instruments.Bass,
        stringQty: 7,
        stringTunings: [11, 4, 9, 2, 7, 11, 4],
      },
    ],
  },
  [Instruments.Keys]: {
    0: [],
  },
};

export const STRING_QTY_OPTIONS: Record<Instruments, StringQty[]> = {
  [Instruments.Guitar]: [6, 7, 8, 9, 10],
  [Instruments.Bass]: [4, 5, 6, 7],
  [Instruments.Keys]: [],
};
